// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/comms.proto

package protocol_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataPointState int32

const (
	DataPointState_EXIT     DataPointState = 0
	DataPointState_INACTIVE DataPointState = 1
	DataPointState_ENTER    DataPointState = 2
	DataPointState_SAMPLE   DataPointState = 3
)

var DataPointState_name = map[int32]string{
	0: "EXIT",
	1: "INACTIVE",
	2: "ENTER",
	3: "SAMPLE",
}

var DataPointState_value = map[string]int32{
	"EXIT":     0,
	"INACTIVE": 1,
	"ENTER":    2,
	"SAMPLE":   3,
}

func (x DataPointState) String() string {
	return proto.EnumName(DataPointState_name, int32(x))
}

func (DataPointState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_391cdfe48e9ebcdb, []int{0}
}

type RegisterRequest struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MachineName          string   `protobuf:"bytes,2,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_391cdfe48e9ebcdb, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *RegisterRequest) GetMachineName() string {
	if m != nil {
		return m.MachineName
	}
	return ""
}

func (m *RegisterRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DataPoint struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Label                string               `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	State                DataPointState       `protobuf:"varint,3,opt,name=state,proto3,enum=timekeeper.DataPointState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DataPoint) Reset()         { *m = DataPoint{} }
func (m *DataPoint) String() string { return proto.CompactTextString(m) }
func (*DataPoint) ProtoMessage()    {}
func (*DataPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_391cdfe48e9ebcdb, []int{1}
}

func (m *DataPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPoint.Unmarshal(m, b)
}
func (m *DataPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPoint.Marshal(b, m, deterministic)
}
func (m *DataPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPoint.Merge(m, src)
}
func (m *DataPoint) XXX_Size() int {
	return xxx_messageInfo_DataPoint.Size(m)
}
func (m *DataPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPoint.DiscardUnknown(m)
}

var xxx_messageInfo_DataPoint proto.InternalMessageInfo

func (m *DataPoint) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DataPoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *DataPoint) GetState() DataPointState {
	if m != nil {
		return m.State
	}
	return DataPointState_EXIT
}

type SendDataRequest struct {
	DataPoints           []*DataPoint `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Id                   uint64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendDataRequest) Reset()         { *m = SendDataRequest{} }
func (m *SendDataRequest) String() string { return proto.CompactTextString(m) }
func (*SendDataRequest) ProtoMessage()    {}
func (*SendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_391cdfe48e9ebcdb, []int{2}
}

func (m *SendDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataRequest.Unmarshal(m, b)
}
func (m *SendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataRequest.Marshal(b, m, deterministic)
}
func (m *SendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataRequest.Merge(m, src)
}
func (m *SendDataRequest) XXX_Size() int {
	return xxx_messageInfo_SendDataRequest.Size(m)
}
func (m *SendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataRequest proto.InternalMessageInfo

func (m *SendDataRequest) GetDataPoints() []*DataPoint {
	if m != nil {
		return m.DataPoints
	}
	return nil
}

func (m *SendDataRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_391cdfe48e9ebcdb, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SendDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataResponse) Reset()         { *m = SendDataResponse{} }
func (m *SendDataResponse) String() string { return proto.CompactTextString(m) }
func (*SendDataResponse) ProtoMessage()    {}
func (*SendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_391cdfe48e9ebcdb, []int{4}
}

func (m *SendDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataResponse.Unmarshal(m, b)
}
func (m *SendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataResponse.Marshal(b, m, deterministic)
}
func (m *SendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataResponse.Merge(m, src)
}
func (m *SendDataResponse) XXX_Size() int {
	return xxx_messageInfo_SendDataResponse.Size(m)
}
func (m *SendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("timekeeper.DataPointState", DataPointState_name, DataPointState_value)
	proto.RegisterType((*RegisterRequest)(nil), "timekeeper.RegisterRequest")
	proto.RegisterType((*DataPoint)(nil), "timekeeper.DataPoint")
	proto.RegisterType((*SendDataRequest)(nil), "timekeeper.SendDataRequest")
	proto.RegisterType((*RegisterResponse)(nil), "timekeeper.RegisterResponse")
	proto.RegisterType((*SendDataResponse)(nil), "timekeeper.SendDataResponse")
}

func init() {
	proto.RegisterFile("proto/comms.proto", fileDescriptor_391cdfe48e9ebcdb)
}

var fileDescriptor_391cdfe48e9ebcdb = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0x4d, 0xfa, 0x41, 0x72, 0x52, 0xda, 0x74, 0x50, 0x28, 0x51, 0xb1, 0xe6, 0xaa, 0x78,
	0x91, 0x4a, 0x04, 0xf1, 0x4e, 0x8a, 0xe6, 0xa2, 0xa8, 0xa5, 0x4c, 0x82, 0xe8, 0x55, 0x99, 0x26,
	0x67, 0xbb, 0xc3, 0x36, 0x1f, 0x9b, 0x99, 0xee, 0x5b, 0xec, 0x43, 0xec, 0x9b, 0x2e, 0xf9, 0xde,
	0x96, 0xde, 0xcd, 0xcc, 0xf9, 0x71, 0xce, 0xff, 0x77, 0x06, 0xa6, 0x59, 0x9e, 0xca, 0x74, 0x19,
	0xa6, 0x71, 0x2c, 0x9c, 0xf2, 0x4c, 0x40, 0xf2, 0x18, 0xef, 0x10, 0x33, 0xcc, 0xad, 0x0f, 0x87,
	0x34, 0x3d, 0x1c, 0x71, 0x59, 0x56, 0xf6, 0xa7, 0x9b, 0x65, 0x51, 0x13, 0x92, 0xc5, 0x59, 0x05,
	0xdb, 0x21, 0x4c, 0x28, 0x1e, 0xb8, 0x90, 0x98, 0x53, 0xbc, 0x3f, 0xa1, 0x90, 0xe4, 0x3d, 0x00,
	0xcf, 0x76, 0x2c, 0x8a, 0x72, 0x14, 0x62, 0xa6, 0xcc, 0x95, 0x85, 0x4e, 0x75, 0x9e, 0xad, 0xaa,
	0x07, 0xf2, 0x11, 0x46, 0x31, 0x0b, 0x6f, 0x79, 0x82, 0xbb, 0x84, 0xc5, 0x38, 0x53, 0x4b, 0xc0,
	0xa8, 0xdf, 0x36, 0x2c, 0x46, 0x32, 0x06, 0x95, 0x47, 0xb3, 0xde, 0x5c, 0x59, 0xf4, 0xa9, 0xca,
	0x23, 0xfb, 0x51, 0x01, 0xfd, 0x27, 0x93, 0x6c, 0x9b, 0xf2, 0x44, 0x92, 0x6f, 0xa0, 0xb7, 0x29,
	0xca, 0xf6, 0x86, 0x6b, 0x39, 0x55, 0x4e, 0xa7, 0xc9, 0xe9, 0x04, 0x0d, 0x41, 0x3b, 0x98, 0xbc,
	0x86, 0xc1, 0x91, 0xed, 0xf1, 0x58, 0xcf, 0xac, 0x2e, 0xe4, 0x33, 0x0c, 0x84, 0x64, 0x12, 0xcb,
	0x81, 0x63, 0xd7, 0x72, 0x3a, 0x7f, 0xa7, 0x9d, 0xea, 0x17, 0x04, 0xad, 0x40, 0xfb, 0x3f, 0x4c,
	0x7c, 0x4c, 0xa2, 0xa2, 0xd8, 0x48, 0x7f, 0x05, 0x23, 0x62, 0x92, 0xed, 0xb2, 0x02, 0x2e, 0xac,
	0x7b, 0x0b, 0xc3, 0x7d, 0x73, 0xb5, 0x15, 0x85, 0xa8, 0x39, 0x8a, 0x5a, 0x55, 0x6d, 0x55, 0x6d,
	0x30, 0xbb, 0x7d, 0x8a, 0x2c, 0x4d, 0x44, 0xb3, 0x0e, 0xa5, 0x65, 0x08, 0x98, 0xdd, 0xf8, 0x8a,
	0xf9, 0xf4, 0x1d, 0xc6, 0xe7, 0x59, 0x89, 0x06, 0x7d, 0xef, 0xdf, 0x3a, 0x30, 0x5f, 0x91, 0x11,
	0x68, 0xeb, 0xcd, 0xea, 0x47, 0xb0, 0xfe, 0xeb, 0x99, 0x0a, 0xd1, 0x61, 0xe0, 0x6d, 0x02, 0x8f,
	0x9a, 0x2a, 0x01, 0x18, 0xfa, 0xab, 0x3f, 0xdb, 0xdf, 0x9e, 0xd9, 0x73, 0x9f, 0x14, 0x98, 0x16,
	0x4b, 0xfb, 0x55, 0xa6, 0xf5, 0x31, 0x7f, 0xe0, 0x21, 0x12, 0x0f, 0xb4, 0x26, 0x0e, 0x79, 0xfb,
	0xd2, 0xe6, 0xe2, 0xd3, 0xad, 0x77, 0xd7, 0x8b, 0xb5, 0x81, 0x07, 0x5a, 0x93, 0xf8, 0xbc, 0xcd,
	0xc5, 0x1a, 0xcf, 0xdb, 0x5c, 0x4a, 0xee, 0x87, 0xe5, 0xf7, 0x7e, 0x79, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x06, 0x86, 0x8c, 0xc4, 0xb5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TimeKeeperServiceClient is the client API for TimeKeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeKeeperServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	SendData(ctx context.Context, in *SendDataRequest, opts ...grpc.CallOption) (*SendDataResponse, error)
}

type timeKeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeKeeperServiceClient(cc grpc.ClientConnInterface) TimeKeeperServiceClient {
	return &timeKeeperServiceClient{cc}
}

func (c *timeKeeperServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/timekeeper.TimeKeeperService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeKeeperServiceClient) SendData(ctx context.Context, in *SendDataRequest, opts ...grpc.CallOption) (*SendDataResponse, error) {
	out := new(SendDataResponse)
	err := c.cc.Invoke(ctx, "/timekeeper.TimeKeeperService/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeKeeperServiceServer is the server API for TimeKeeperService service.
type TimeKeeperServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	SendData(context.Context, *SendDataRequest) (*SendDataResponse, error)
}

// UnimplementedTimeKeeperServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTimeKeeperServiceServer struct {
}

func (*UnimplementedTimeKeeperServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedTimeKeeperServiceServer) SendData(ctx context.Context, req *SendDataRequest) (*SendDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}

func RegisterTimeKeeperServiceServer(s *grpc.Server, srv TimeKeeperServiceServer) {
	s.RegisterService(&_TimeKeeperService_serviceDesc, srv)
}

func _TimeKeeperService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeKeeperServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timekeeper.TimeKeeperService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeKeeperServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeKeeperService_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeKeeperServiceServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timekeeper.TimeKeeperService/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeKeeperServiceServer).SendData(ctx, req.(*SendDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeKeeperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timekeeper.TimeKeeperService",
	HandlerType: (*TimeKeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TimeKeeperService_Register_Handler,
		},
		{
			MethodName: "SendData",
			Handler:    _TimeKeeperService_SendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/comms.proto",
}
