// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comms.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataPointState int32

const (
	DataPointState_EXIT     DataPointState = 0
	DataPointState_INACTIVE DataPointState = 1
	DataPointState_ENTER    DataPointState = 2
	DataPointState_SAMPLE   DataPointState = 3
)

var DataPointState_name = map[int32]string{
	0: "EXIT",
	1: "INACTIVE",
	2: "ENTER",
	3: "SAMPLE",
}

var DataPointState_value = map[string]int32{
	"EXIT":     0,
	"INACTIVE": 1,
	"ENTER":    2,
	"SAMPLE":   3,
}

func (x DataPointState) String() string {
	return proto.EnumName(DataPointState_name, int32(x))
}

func (DataPointState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

type RegisterRequest struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MachineName          string   `protobuf:"bytes,2,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`
	TrackerName          string   `protobuf:"bytes,3,opt,name=tracker_name,json=trackerName,proto3" json:"tracker_name,omitempty"`
	Id                   uint64   `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *RegisterRequest) GetMachineName() string {
	if m != nil {
		return m.MachineName
	}
	return ""
}

func (m *RegisterRequest) GetTrackerName() string {
	if m != nil {
		return m.TrackerName
	}
	return ""
}

func (m *RegisterRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DataPoint struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Label                string               `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	State                DataPointState       `protobuf:"varint,3,opt,name=state,proto3,enum=timekeeper.DataPointState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DataPoint) Reset()         { *m = DataPoint{} }
func (m *DataPoint) String() string { return proto.CompactTextString(m) }
func (*DataPoint) ProtoMessage()    {}
func (*DataPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{1}
}

func (m *DataPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPoint.Unmarshal(m, b)
}
func (m *DataPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPoint.Marshal(b, m, deterministic)
}
func (m *DataPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPoint.Merge(m, src)
}
func (m *DataPoint) XXX_Size() int {
	return xxx_messageInfo_DataPoint.Size(m)
}
func (m *DataPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPoint.DiscardUnknown(m)
}

var xxx_messageInfo_DataPoint proto.InternalMessageInfo

func (m *DataPoint) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DataPoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *DataPoint) GetState() DataPointState {
	if m != nil {
		return m.State
	}
	return DataPointState_EXIT
}

type SendDataRequest struct {
	DataPoints []*DataPoint `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	// hope to get rid of this, should not be needed as a field, but as metadata
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataRequest) Reset()         { *m = SendDataRequest{} }
func (m *SendDataRequest) String() string { return proto.CompactTextString(m) }
func (*SendDataRequest) ProtoMessage()    {}
func (*SendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{2}
}

func (m *SendDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataRequest.Unmarshal(m, b)
}
func (m *SendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataRequest.Marshal(b, m, deterministic)
}
func (m *SendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataRequest.Merge(m, src)
}
func (m *SendDataRequest) XXX_Size() int {
	return xxx_messageInfo_SendDataRequest.Size(m)
}
func (m *SendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataRequest proto.InternalMessageInfo

func (m *SendDataRequest) GetDataPoints() []*DataPoint {
	if m != nil {
		return m.DataPoints
	}
	return nil
}

func (m *SendDataRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SendDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataResponse) Reset()         { *m = SendDataResponse{} }
func (m *SendDataResponse) String() string { return proto.CompactTextString(m) }
func (*SendDataResponse) ProtoMessage()    {}
func (*SendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{4}
}

func (m *SendDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataResponse.Unmarshal(m, b)
}
func (m *SendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataResponse.Marshal(b, m, deterministic)
}
func (m *SendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataResponse.Merge(m, src)
}
func (m *SendDataResponse) XXX_Size() int {
	return xxx_messageInfo_SendDataResponse.Size(m)
}
func (m *SendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("timekeeper.DataPointState", DataPointState_name, DataPointState_value)
	proto.RegisterType((*RegisterRequest)(nil), "timekeeper.RegisterRequest")
	proto.RegisterType((*DataPoint)(nil), "timekeeper.DataPoint")
	proto.RegisterType((*SendDataRequest)(nil), "timekeeper.SendDataRequest")
	proto.RegisterType((*RegisterResponse)(nil), "timekeeper.RegisterResponse")
	proto.RegisterType((*SendDataResponse)(nil), "timekeeper.SendDataResponse")
}

func init() {
	proto.RegisterFile("comms.proto", fileDescriptor_db39efb7717b7d47)
}

var fileDescriptor_db39efb7717b7d47 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x41, 0x8f, 0xd2, 0x40,
	0x18, 0x86, 0x9d, 0x02, 0x1b, 0xf8, 0x40, 0xb6, 0x3b, 0xd1, 0x48, 0x70, 0x8d, 0x6b, 0x4f, 0x84,
	0x43, 0xab, 0x98, 0x6c, 0xcc, 0x1a, 0x63, 0x50, 0x39, 0x10, 0x95, 0x6c, 0x0a, 0x31, 0xea, 0x41,
	0x32, 0xb4, 0x9f, 0xec, 0x04, 0x3a, 0x53, 0x3b, 0xc3, 0xfe, 0x00, 0x0f, 0xde, 0x3c, 0xf9, 0xd3,
	0xf4, 0x27, 0xf8, 0x43, 0xcc, 0x74, 0x5a, 0x10, 0xb2, 0xb7, 0xe9, 0xf7, 0x3d, 0x79, 0xe7, 0x7d,
	0xdf, 0x4c, 0xa1, 0x19, 0xc9, 0x24, 0x51, 0x7e, 0x9a, 0x49, 0x2d, 0x29, 0x68, 0x9e, 0xe0, 0x0a,
	0x31, 0xc5, 0xac, 0xfb, 0x70, 0x29, 0xe5, 0x72, 0x8d, 0x41, 0xbe, 0x59, 0x6c, 0xbe, 0x06, 0x66,
	0xa7, 0x34, 0x4b, 0x52, 0x0b, 0x77, 0x4f, 0x0b, 0x80, 0xa5, 0x3c, 0x60, 0x42, 0x48, 0xcd, 0x34,
	0x97, 0xa2, 0x90, 0xf2, 0x7e, 0x10, 0x38, 0x0e, 0x71, 0xc9, 0x95, 0xc6, 0x2c, 0xc4, 0x6f, 0x1b,
	0x54, 0x9a, 0x3e, 0x00, 0xe0, 0xe9, 0x9c, 0xc5, 0x71, 0x86, 0x4a, 0x75, 0xc8, 0x19, 0xe9, 0x35,
	0xc2, 0x06, 0x4f, 0x87, 0x76, 0x40, 0x1f, 0x41, 0x2b, 0x61, 0xd1, 0x15, 0x17, 0x38, 0x17, 0x2c,
	0xc1, 0x8e, 0x93, 0x03, 0xcd, 0x62, 0x36, 0x61, 0x09, 0x1a, 0x44, 0x67, 0x2c, 0x5a, 0x61, 0x66,
	0x91, 0x8a, 0x45, 0x8a, 0x59, 0x8e, 0xb4, 0xc1, 0xe1, 0x71, 0xa7, 0x7a, 0x46, 0x7a, 0xd5, 0xd0,
	0xe1, 0xb1, 0xf7, 0x93, 0x40, 0xe3, 0x0d, 0xd3, 0xec, 0x52, 0x72, 0xa1, 0xe9, 0x33, 0x68, 0x6c,
	0x73, 0xe4, 0x0e, 0x9a, 0x83, 0xae, 0x6f, 0x83, 0xf8, 0x65, 0x52, 0x7f, 0x56, 0x12, 0xe1, 0x0e,
	0xa6, 0x77, 0xa0, 0xb6, 0x66, 0x0b, 0x5c, 0x17, 0xb6, 0xec, 0x07, 0x7d, 0x0c, 0x35, 0xa5, 0x99,
	0xb6, 0x4e, 0xda, 0x83, 0xae, 0xbf, 0x6b, 0xd0, 0xdf, 0xde, 0x3a, 0x35, 0x44, 0x68, 0x41, 0xef,
	0x13, 0x1c, 0x4f, 0x51, 0xc4, 0x66, 0x59, 0xf6, 0x72, 0x0e, 0xcd, 0x98, 0x69, 0x36, 0x4f, 0x0d,
	0x6c, 0x8a, 0xa9, 0xf4, 0x9a, 0x83, 0xbb, 0x37, 0x4a, 0x85, 0x10, 0x97, 0x47, 0x55, 0x44, 0x75,
	0xb6, 0x51, 0x3d, 0x70, 0x77, 0x95, 0xab, 0x54, 0x0a, 0x55, 0xd6, 0x41, 0xb6, 0x0c, 0x05, 0x77,
	0x77, 0xbd, 0x65, 0xfa, 0x2f, 0xa1, 0xbd, 0xef, 0x95, 0xd6, 0xa1, 0x3a, 0xfa, 0x38, 0x9e, 0xb9,
	0xb7, 0x68, 0x0b, 0xea, 0xe3, 0xc9, 0xf0, 0xf5, 0x6c, 0xfc, 0x61, 0xe4, 0x12, 0xda, 0x80, 0xda,
	0x68, 0x32, 0x1b, 0x85, 0xae, 0x43, 0x01, 0x8e, 0xa6, 0xc3, 0xf7, 0x97, 0xef, 0x46, 0x6e, 0x65,
	0xf0, 0x87, 0xc0, 0x89, 0x29, 0xed, 0x6d, 0xee, 0x76, 0x8a, 0xd9, 0x35, 0x8f, 0x90, 0x7e, 0x81,
	0x7a, 0x69, 0x87, 0xde, 0xff, 0x3f, 0xcd, 0xc1, 0xbb, 0xe8, 0x9e, 0xde, 0xbc, 0xb4, 0xee, 0xbc,
	0x7b, 0xdf, 0x7f, 0xff, 0xfd, 0xe5, 0x9c, 0x78, 0xad, 0xe0, 0xfa, 0x49, 0x90, 0x15, 0xdb, 0x0b,
	0xd2, 0xa7, 0x73, 0xa8, 0x97, 0x51, 0xf6, 0xf5, 0x0f, 0xfa, 0xdd, 0xd7, 0x3f, 0x4c, 0xef, 0x75,
	0x72, 0x7d, 0xea, 0xdd, 0x36, 0xfa, 0x0a, 0x45, 0x3c, 0x37, 0x15, 0x5f, 0x90, 0xfe, 0xab, 0x17,
	0x9f, 0x9f, 0x2f, 0xb9, 0xbe, 0xda, 0x2c, 0xfc, 0x48, 0x26, 0x01, 0x13, 0x71, 0x86, 0x5c, 0x69,
	0x26, 0x06, 0xe7, 0xc1, 0x2e, 0x6d, 0x90, 0xae, 0x96, 0xf6, 0x27, 0x89, 0xe4, 0xda, 0x48, 0x94,
	0xcf, 0x68, 0x71, 0x94, 0x9f, 0x9e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x2e, 0x18, 0x7d,
	0x63, 0x03, 0x00, 0x00,
}
